# ============================================================
# 🚢 docker-compose.yml — Orchestration du conteneur
# ============================================================
# Docker Compose permet de lancer et configurer des conteneurs facilement.
# Au lieu de taper une longue commande 'docker run...', on utilise ce fichier.
# ============================================================

services:
  # Traefik - Le Reverse Proxy
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  # On donne un nom à notre service (notre application)
  mon-api:
    # 'build: .' dit à Docker de construire l'image en utilisant le Dockerfile local.
    build: .

    # Nom que portera le conteneur quand il sera lancé.
    container_name: api_node_apprentissage

    # MAPPING DES PORTS (Hôte:Conteneur)
    # Plus besoin d'exposer le port 3000 directement si on passe par Traefik
    # ports:
    #   - "3000:3000"

    # VOLUMES (Persistance des données)
    # On lie le dossier 'data' de notre ordi au dossier 'data' du conteneur.
    volumes:
      - ./data:/app/data

    # Traefik Labels
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mon-api.rule=Host(`api-demo@codenumx.com`)"
      - "traefik.http.routers.mon-api.entrypoints=web"
      - "traefik.http.services.mon-api.loadbalancer.server.port=3000"

    # Redémarrage automatique si le serveur plante.
    restart: always
    networks:
      - web

networks:
  web:
    external: false
